name: Deploy Smart Portal
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Inject Secrets
        run: |
          # ระบุตำแหน่งไฟล์ index.html ที่อยู่ในโฟลเดอร์ย่อย
          sed -i "s|{{SUPABASE_SMARTSERVICES_URL}}|${{ secrets.SUPABASE_SMARTSERVICES_URL }}|g" smartservices/index.html
          sed -i "s|{{SUPABASE_SMARTSERVICES_ANON_KEY}}|${{ secrets.SUPABASE_SMARTSERVICES_ANON_KEY }}|g" smartservices/index.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # ระบุโฟลเดอร์ย่อยที่เป็นตัวเก็บไฟล์สำหรับแสดงผล
          folder: smartservices 
          branch: gh-pages
